# This is a basic workflow to help you get started with Actions

name: Build CV

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.typ'
      - '**/*.toml'
      - '.github/workflows/cv_build.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Fonts
        run: |
          fontist update
          fontist install "Source Sans Pro"
          fontist install "Roboto"
          fontist install "Font Awesome 6 Free"
          fontist install "Font Awesome 6 Brands"

      - name: Create secrets.toml
        run: echo "${{ secrets.CV_METADATA_SECRETS }}" | base64 -d > secrets.toml
        shell: bash

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 'latest'
          font-path: ~/.fontist/fonts

      - name: Compile CV Document
        run: typst compile cv.typ cv_en.pdf --input lang=en

      - name: Compile CV Document
        run: typst compile cv.typ cv_de.pdf --input lang=de

      - name: Upload Artifact en
        uses: actions/upload-artifact@v4
        with:
          name: compiled-cv-en
          path: cv_en.pdf

      - name: Upload Artifact de
        uses: actions/upload-artifact@v4
        with:
          name: compiled-cv-de
          path: cv_de.pdf
        
