# This is a basic workflow to help you get started with Actions

name: Build CV

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    paths:
      - '**/*.typ'
      - '**/*.toml'
      - '.github/workflows/cv_build.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create secrets.toml
        run: echo "${{ secrets.CV_METADATA_SECRETS }}" > secrets.toml
        shell: bash

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: 'latest'

      - name: Compile CV Document
        run: typst compile cv.typ

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-cv
          path: CV_en.pdf
